# Publishes a NPM package if the version number changes in the `package.json` file. This allows us to only publish
# changes affecting the transactional templates, without causing a release for marketing template changes.
# @see https://github.com/marketplace/actions/npm-publish

name: CI

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 10
      - run: npm install
      - run: npm run prep
      # Only build transactional emails for simplicity.
      # Campaign templates are manually copy/pasted to Intercom.
      # Building in CI requires fixes for OS agnostic usage of `sed` command in `npm run prepare:intercom`
      - run: npm run build:transactional
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
